### ISSUE TITLE
Separate dataframes for dual quantities

### ISSUE THREAD

**Issue by Elhamyali** [Elhamyali/clf-climate-label-study#21]
Construct a new dataframe for entries with a second quantity and unit. Clean the original dataframe by dropping the second quantity/unit column and then concatenate the two dataframes.

From Brent:

Quantity and unit 1

1. Split column to separate quantity and unit, for the delimiter use the space before the first non-numeric character that isn’t “/” or “.”
2. Convert quantity to string
3. Replace fractions with decimals, e.g., “2 1/2" becomes “2.5”. We can probably use a lookup table for this since there’s presumably a very small number of different fractions, e.g., ½, ¼, ¾, etc. https://stackoverflow.com/questions/46342492/use-dictionary-to-replace-a-string-within-a-string-in-pandas-columns
4. Apply a filter to exclude rows with units like “hours,” “minutes,” etc.
5. If “unit” is empty, grab the unit from quantity and unit 2

Quantity and unit 2

- Q: How was quantity and unit 2 separated?
- Repeat steps 1-4 for quantity and unit 1
- Create a separate dataframe (df2) for all the ingredients w/a second quantity and unit 2
- In df, drop quant/unit 2
- In df2, drop quant/unit 1 and rename quant/unit 2 to quant/unit 1
- Concat df and df2

**Comment by brentforest** [comment]
Addressed w/new function stack_ingredient_quant_unit_pairs, included in new .py script (will upload Friday)
